version: '3.8'  # La version correcte pour Docker Compose

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8089:8000"
    env_file:
      - .env
    entrypoint: /app/entrypoint.sh  # Cette ligne doit être dans le service, pas à l'extérieur
