# Generated by Django 5.1.2 on 2024-12-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_order', '0002_rename_sku_product_reference_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('INCREASE', 'Increase'), ('DECREASE ', 'Decrease')], default=1, max_length=255),
            preserve_default=False,
        ),
    ]
