# Generated by Django 5.1.2 on 2024-12-04 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_order', '0004_rename_quantity_in_stock_product_stock_quantity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='min_threshold',
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom du fournisseur')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Adresse e-mail')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Numéro de téléphone')),
                ('address', models.TextField(verbose_name='Adresse')),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='providers_in_manage_order', to='manage_order.product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('In_progress', 'En cours'), ('Completed', 'Terminée'), ('Canceled', 'Annulée')], default='pending', max_length=20, verbose_name='Statut de la commande')),
                ('order_date', models.DateField(auto_now_add=True, verbose_name='Date de la commande')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantité')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix total')),
                ('delivery_address', models.TextField(blank=True, null=True, verbose_name='Adresse de livraison')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Commande payée')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_order.product', verbose_name='Produit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_order.provider', verbose_name='Fournisseur')),
            ],
        ),
    ]
