# Generated by Django 5.1.2 on 2024-12-02 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_user', '0002_remove_user_organization_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom du fournisseur')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Adresse e-mail')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Numéro de téléphone')),
                ('address', models.TextField(verbose_name='Adresse')),
            ],
        ),
    ]
