# Generated by Django 5.1.2 on 2024-12-03 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_order', '0001_initial'),
        ('manager_user', '0004_product_provider_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='Product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='manage_order.product'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
