# Generated by Django 5.1.2 on 2024-12-04 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_order', '0005_remove_product_min_threshold_provider_order'),
        ('manager_user', '0005_alter_provider_product_delete_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='Product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='manage_order.product'),
        ),
    ]
