# Generated by Django 5.1.2 on 2024-12-10 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager_user', '0006_alter_provider_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Provider',
        ),
    ]
